services:
  front-prod:
    image: ghcr.io/benajabendo/le-creuset-front:front-prod
    container_name: lecreuset-front-prod
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front-prod.rule=Host(`lecreuset.benaja-bendo.fr`)"
      - "traefik.http.routers.front-prod.entrypoints=websecure"
      - "traefik.http.routers.front-prod.tls.certresolver=myresolver"
      - "traefik.http.services.front-prod.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
